// react_js/jsview/samples/basic/div/DivClip.js
import React from 'react';
import testImgPath from '../resources/test.jpg';

class DivLayout extends React.Component {
  render() {
    const imageShowWidth = 80;
    const imageShowHeight = 64;
    const clipWidth = 50;
    const clipHeight = 40;

    const FontBase = {
      fontFamily: '黑体',
      fontSize: '12px',
    };

    const titleHeight = 16;

    return (<div id='layout-root' style={this.props.style}>
                <div style={{ top: 0 }}>
                    <div style={{ ...FontBase, width: 50, height: titleHeight }}>原图</div>
                    <div style={{ top: titleHeight,
                      width: imageShowWidth + 4,
                      height: imageShowHeight + 4,
                      backgroundColor: 'rgba(0, 255, 0, 1)' }}>
                        <div style={{ left: 2,
                          top: 2,
                          width: imageShowWidth,
                          height: imageShowHeight,
                          backgroundImage: `url(${testImgPath})` }}/>
                    </div>
                </div>
                <div style={{ top: imageShowHeight + titleHeight + 4 }}>
                    <div style={{ ...FontBase, width: 120, height: titleHeight }}>左上Overflow</div>
                    <div style={{ top: titleHeight,
                      width: imageShowWidth + 4,
                      height: imageShowHeight + 4,
                      backgroundColor: 'rgba(0, 255, 0, 1)' }}>
                        <div key="clipArea" style={{ left: 2,
                          top: 2,
                          width: clipWidth,
                          height: clipHeight,
                          overflow: "hidden" }}>
                            <div style={{ width: imageShowWidth,
                              height: imageShowHeight,
                              backgroundImage: `url(${testImgPath})` }}/>
                        </div>
                    </div>
                </div>
                <div style={{ top: (imageShowHeight + titleHeight + 4) * 2 }}>
                    <div style={{ ...FontBase, width: 120, height: titleHeight }}>右下Overflow</div>
                    <div style={{ top: titleHeight,
                      width: imageShowWidth + 4,
                      height: imageShowHeight + 4,
                      backgroundColor: 'rgba(0, 255, 0, 1)' }}>
                        <div key="clipArea" style={{ top: 2 + (imageShowHeight - clipHeight),
                          left: 2 + (imageShowWidth - clipWidth),
                          width: clipWidth,
                          height: clipHeight,
                          overflow: "hidden" }}>
                            <div style={{ top: -((imageShowHeight - clipHeight)),
                              left: -(imageShowWidth - clipWidth),
                              width: imageShowWidth,
                              height: imageShowHeight,
                              backgroundImage: `url(${testImgPath})` }}/>
                        </div>
                    </div>
                </div>
                <div style={{ top: (imageShowHeight + titleHeight + 4), left: imageShowWidth + 16 }}>
                    <div style={{ ...FontBase, width: 100, height: titleHeight }}>ClipPath</div>
                    <div style={{ top: titleHeight,
                      width: imageShowWidth + 4,
                      height: imageShowHeight + 4,
                      backgroundColor: 'rgba(0, 255, 0, 1)' }}>
                        <div key="clipArea" style={{ left: 2,
                          top: 2,
                          width: imageShowWidth,
                          height: imageShowHeight,
                          clipPath: 'inset(5px 10px 15px 20px)'/* margin of top, right, bottom, left */ }}>
                            <div style={{ width: imageShowWidth,
                              height: imageShowHeight,
                              backgroundImage: `url(${testImgPath})` }}/>
                        </div>
                    </div>
                </div>
            </div>);
  }
}

export default DivLayout;

// vue3_js/jsview/samples/basic/components/div/DivClip.vue
<template>
<div id='layout-root'>
    <div style="{top: 0}">
        <div :style="{...ContentFont, width: 50, height: titleHeight}">原图</div>
        <div :style="{top: titleHeight,
            width: imageSize.width+4, height: imageSize.height+4,
            backgroundColor: 'rgba(0, 255, 0, 1)' }">
            <div :style="{ left: 2, top: 2,
                width: imageSize.width, height: imageSize.height,
                backgroundImage: `url(${testImgPath})` }"/>
        </div>
    </div>

    <div :style="{top: imageSize.height+titleHeight+4}">
        <div :style="{ ...ContentFont, width: 120, height: titleHeight }">左上Overflow</div>
        <div :style="{ top: titleHeight,
            width: imageSize.width+4, height: imageSize.height+4,
            backgroundColor: 'rgba(0, 255, 0, 1)' }">
            <div key="clipArea" :style="{ left: 2, top: 2,
                width: clipSize.width, height: clipSize.height,
                overflow: 'hidden' }">
                <div :style="{ width: imageSize.width,
                    height: imageSize.height,
                    backgroundImage: `url(${testImgPath})` }"/>
            </div>
        </div>
    </div>

    <div :style="{ top: (imageSize.height+titleHeight+4)*2 }">
        <div :style="{ ...ContentFont, width: 120, height: titleHeight }">右下Overflow</div>
        <div :style="{ top: titleHeight,
            width: imageSize.width+4, height: imageSize.height+4,
            backgroundColor: 'rgba(0, 255, 0, 1)' }">
            <div key="clipArea" :style="{ top: 2+(imageSize.height-clipSize.height),
                left: 2+(imageSize.width-clipSize.width),
                width: clipSize.width, height: clipSize.height,
                overflow: 'hidden' }">
                <div :style="{ top: -((imageSize.height-clipSize.height)),
                    left: -(imageSize.width-clipSize.width),
                    width: imageSize.width, height: imageSize.height,
                    backgroundImage: `url(${testImgPath})` }"/>
            </div>
        </div>
    </div>

    <div :style="{ top: imageSize.height+titleHeight+4, left: imageSize.width+16 }">
        <div :style="{ ...ContentFont, width: 100, height: titleHeight }">ClipPath</div>
        <div :style="{ top: titleHeight,
            width: imageSize.width+4, height: imageSize.height+4,
            backgroundColor: 'rgba(0, 255, 0, 1)' }">
            <div key="clipArea" :style="{ left: 2, top: 2,
                width: imageSize.width, height: imageSize.height,
                clipPath: 'inset(5px 10px 15px 20px)'/* margin of top, right, bottom, left */ }">
                <div :style="{ width: imageSize.width, height: imageSize.height,
                    backgroundImage: `url(${testImgPath})` }"/>
            </div>
        </div>
    </div>

</div>
</template>

<script setup>
import { ContentFont } from '../../FontStyle';
import testImgPath from '../../assets/test.jpg';

</script>

<script jsv-style>
const titleHeight = 16;
const imageSize = {
    width: 80,
    height: 64,
};
const clipSize = {
    width: 50,
    height: 40,
};
</script>
