// vue3_js/jsview/samples/basic/components/div/DivBackground.vue
<template>
<div id='layout-root'>
    <div :style="{ ...ContentFont, width: 180, height: 50, backgroundColor: 'rgba(255, 255, 0, 1)' }">style.backgroundColor</div>
    <div :style="{ ...ContentFont, top: 60, width: 180, height: 50, backgroundImage: `url(${iconImgPath})` }">style.backgroundImage</div>
</div>;
</template>

<script setup>
import { ContentFont } from '../../FontStyle';
import iconImgPath from '../../assets/icon.png';
</script>

// react_js/src/basic/div/DivBackground.js
import React from 'react';
import iconImgPath from '../resources/icon.png';
import { TitleFont as baseFont } from '../CommonFontStyle';

class DivLayout extends React.Component {
  render() {
    return <div id='layout-root' style={this.props.style}>
                <div style={{ ...baseFont, width: 180, height: 50, backgroundColor: 'rgba(255, 255, 0, 1)' }}>style.backgroundColor</div>
                <div style={{ ...baseFont, top: 60, width: 180, height: 50, backgroundImage: `url(${iconImgPath})` }}>style.backgroundImage</div>
            </div>;
  }
}

export default DivLayout;
