// vue3_js/jsview/samples/basic/components/div/DivGroup1.vue
<template>
    <div id='item-root'>
        <ContentBlock :=contentBlockProps :index=0 title="Layout(布局定位)" :style="{top:itemSides.height*0}">
             <DivLayout/>
        </ContentBlock>
        <ContentBlock :=contentBlockProps :index=1 title="Background(加载图片)" :style="{top:itemSides.height*1}">
            <DivBackground/>
        </ContentBlock>
        <ContentBlock :="{...contentBlockProps, itemSides: {...itemSides, height:290}}" :index=2 title="Clip(裁剪)" :style="{ top:itemSides.height*2}">
            <DivClip/>
        </ContentBlock>
    </div>
</template>

<script setup>
import { defineProps } from "vue";
import ContentBlock from '../ContentBlock';
import DivBackground from './DivBackground';
import DivClip from './DivClip';
import DivLayout from './DivLayout';

const name = 'DivGroup1';
const props = defineProps({
  contentSize: Object,
  itemSides: Object 
})
</script>


<script jsv-style>
const contentBlockProps = {
    colIndex: 0,
    contentSize: props.contentSize,
    itemSides: props.itemSides
};
</script>

// react_js/src/basic/div/DivGroup1.js
import React from 'react';
import DivLayout from "./DivLayout";
import DivBackground from "./DivBackground";
import DivClip from "./DivClip";
import TitleBlock from "../TitleBlock";

class DivGroup extends React.Component {
  render() {
    const titleBlockProps = { ColIndex: 0, itemWidth: this.props.itemWidth, itemHeight: this.props.itemHeight };

    return <div id='item-root' style={this.props.style}>
            <TitleBlock {...titleBlockProps} LineIndex={0} titleText="Layout(布局定位)" style={{ top: this.props.itemHeight * 0 }}>
                <DivLayout/>
            </TitleBlock>
            <TitleBlock {...titleBlockProps} LineIndex={1} titleText="Background(加载图片)" style={{ top: this.props.itemHeight * 1 }}>
                <DivBackground/>
            </TitleBlock>
            <TitleBlock {...titleBlockProps} itemHeight={this.props.itemHeight * 2} LineIndex={2} titleText="Clip(裁剪)" style={{ top: this.props.itemHeight * 2 }}>
                <DivClip/>
            </TitleBlock>
        </div>;
  }
}

export default DivGroup;
