// vue3_js/jsview/samples/basic/components/anim/AnimGroup.vue
<template>
    <div id='item-root'>
        <ContentBlock
            :class=contentClass
            :style="{ top: itemSides.height * 0 }"
            :=contentBlockProps
            :index=1
            title="Keyframe基础动画集合">
            <AnimKeyframeBasic/>
        </ContentBlock>
        <ContentBlock
            :class=contentClass
            :style="{ top: itemSides.height * 1 }"
            :=contentBlockProps
            :index=2
            title="Keyframe组合示例">
            <AnimKeyframeComposite/>
        </ContentBlock>
        <ContentBlock
            :class=contentClass
            :style="{ top: itemSides.height * 2}"
            :="{...contentBlockProps, itemSides: {...itemSides, height:290}}"
            :index=3
            title="Transition动画示例">
            <AnimTransition :timeCount=state.timeCount />
        </ContentBlock>
    </div>

</template>

<script setup>
/* eslint-disable no-unused-vars */
import { defineProps, reactive, onMounted, onBeforeUnmount } from "vue";
import ContentBlock from '../ContentBlock';
import AnimKeyframeBasic from './AnimKeyframeBasic';
import AnimKeyframeComposite from './AnimKeyframeComposite';
import AnimTransition from './AnimTransition';

const name = 'DivGroup2';
const props = defineProps({
  contentClass: String,
  itemSides: Object 
})

const state = reactive({
    timeCount: 20
})
var timerId = -1;

onMounted(() => {
    timerId = setInterval(() => {
        // console.log('change timeCount: ' + timeCount);
        state.timeCount = (state.timeCount + 5);
    }, 2000);
});

onBeforeUnmount(() => {
    if (timerId >= 0) {
      window.clearInterval(timerId);
    }
    timerId = -1;
});

const contentBlockProps = {
    colIndex: 0,
    itemSides: props.itemSides
};
</script>

// react_js/jsview/samples/basic/anim/AnimGroup.js
import React from 'react';
import AnimKeyframeBasic from "./AnimKeyframeBasic";
import AnimKeyframeComposite from "./AnimKeyframeComposite";
import AnimTransition from "./AnimTransition";
import TitleBlock from "../TitleBlock";

class AnimGroup extends React.Component {
  constructor(props) {
    super(props);
    console.log("AnimGroup.constructor().");

    this.state = { timeCount: 0 };
    this._Timer = setInterval(() => {
      const count = this.state.timeCount + 5;
      // console.log('change timeCount: ' + count);
      this.setState({ timeCount: count });
    }, 2000);
  }

  render() {
    const titleBlockProps = { ColIndex: 3, itemWidth: this.props.itemWidth, itemHeight: this.props.itemHeight };

    return <div id="item-root" style={this.props.style}>
                <TitleBlock {...titleBlockProps} LineIndex={0} titleText="Keyframe基础动画集合" style={{ top: this.props.itemHeight * 0 }}>
                    <AnimKeyframeBasic/>
                </TitleBlock>
                <TitleBlock {...titleBlockProps} LineIndex={1} titleText="Keyframe组合示例" style={{ top: this.props.itemHeight * 1 }}>
                    <AnimKeyframeComposite/>
                </TitleBlock>
                <TitleBlock {...titleBlockProps} LineIndex={2} titleText="Transition动画示例" style={{ top: this.props.itemHeight * 2 }}>
                    <AnimTransition timeCount={this.state.timeCount}/>
                </TitleBlock>
            </div>;
  }

  componentWillUnmount() {
    if (this._Timer >= 0) {
      window.clearInterval(this._Timer);
      this._Timer = -1;
    }
  }
}

export default AnimGroup;
