// react_js/src/basic/anim/AnimKeyframeBasic.js
import React from 'react';
import './AnimKeyframeBasic.css';
import {ContentFont} from '../CommonFontStyle'

class AnimKeyframeBasic extends React.Component {
    render() {
        const subItemWidth = 70;
        const subItemHeight = 70;
        const titleStyle = {
            ...ContentFont,
            width: 60,
            height: 20,
            textAlign: 'center',
            lineHeight: '20px'
        };

        const blockStyle = {
            top:20,
            width:50,
            height:50,
            backgroundColor:'rgba(255, 0, 0, 1)'
        };

        return <div id='layout-root' style={this.props.style}>
                <div>
                    <div style={{...titleStyle}}>Translate3d</div>
                    <div style={{...blockStyle, animation: 'AnimTranslate 3s infinite'}}/>
                </div>
                <div style={{left:subItemWidth}}>
                    <div style={{...titleStyle}}>Scale3d</div>
                    <div style={{...blockStyle, animation: 'AnimScale 3s infinite linear'}}/>
                </div>
                <div style={{left:subItemWidth * 2}}>
                    <div style={{...titleStyle}}>Rotate3d</div>
                    <div style={{...blockStyle, animation: 'AnimRotate 3s infinite linear'}}/>
                </div>
                <div style={{left:subItemWidth, top:subItemHeight}}>
                    <div style={{...titleStyle}}>Skew</div>
                    <div style={{...blockStyle, animation: 'AnimSkew 3s infinite ease-in'}}/>
                </div>
                <div style={{left:subItemWidth * 2, top:subItemHeight}}>
                    <div style={{...titleStyle}}>Opacity</div>
                    <div style={{...blockStyle, width:20, animation: 'AnimOpacityOut 3s infinite ease-out'}}/>
                    <div style={{...blockStyle, left:25, width:20, animation: 'AnimOpacityIn 3s infinite ease-in-out'}}/>
                </div>
            </div>
    }
}

export default AnimKeyframeBasic;

// vue3_js/jsview/samples/basic/anim/AnimKeyframeBasic.vue
<template>
<div id='layout-root'>
    <div>
        <div :style="{ ...titleStyle }">Translate3d</div>
        <div :style="{ ...itemStyle, animation: 'AnimTranslate 3s infinite' }"/>
    </div>
    <div :style="{ left: blockSize.width }">
        <div :style="{ ...titleStyle }">Scale3d</div>
        <div :style="{ ...itemStyle, animation: 'AnimScale 3s infinite linear' }"/>
    </div>
    <div :style="{ left: blockSize.width*2 }">
        <div :style="{ ...titleStyle }">Rotate3d</div>
        <div :style="{ ...itemStyle, animation: 'AnimRotate 3s infinite linear' }"/>
    </div>
    <div :style="{ left: blockSize.width, top: blockSize.height }">
        <div :style="{ ...titleStyle }">Skew</div>
        <div :style="{ ...itemStyle, animation: 'AnimSkew 3s infinite ease-in' }"/>
    </div>
    <div :style="{ left: blockSize.width*2, top: blockSize.height }">
        <div :style="{ ...titleStyle }">Opacity</div>
        <div :style="{ ...itemStyle, width: 20, animation: 'AnimOpacityOut 3s infinite ease-out' }"/>
        <div :style="{ ...itemStyle, left: 25, width: 20, animation: 'AnimOpacityIn 3s infinite ease-in-out' }"/>
    </div>
</div>
</template>

<script setup>
import { ContentFont } from '../FontStyle';

</script>

<script jsv-style>
const blockSize = {
    width: 70,
    height: 70,
};

const titleStyle = {
    ...ContentFont,
    width: 60, height: 20,
    textAlign: 'center',
    lineHeight: 20
};

const itemStyle = {
    top: 20,
    width: 50, height: 50,
    backgroundColor: 'rgba(255, 0, 0, 1)'
};

</script>

<style>
@keyframes AnimTranslate {
  from {
    transform: translate3d(50%, 50px, 0);
  }
  to {
    transform: translate3d(0, 0, 0);
  }
}

@keyframes AnimScale {
  from {
    transform: scale3d(1.5, 1.5, 1);
  }
  to {
    transform: scale3d(0, 0, 0);
  }
}

@keyframes AnimRotate {
  from {
    transform: rotate3d(1.5, 1, 1, 90deg);
  }
  to {
    transform: rotate3d(1.5, 1, 1, 0);
  }
}

@keyframes AnimSkew {
  from {
    transform: skew(30deg, 45deg);
  }
  to {
    transform: skew(0, 0);
  }
}

@keyframes AnimOpacityOut {
  from {
    opacity: 0.1;
  }
  to {
    opacity: 1;
  }
}

@keyframes AnimOpacityIn {
  from {
    opacity: 1;
  }
  to {
    opacity: 20%;
  }
}
</style>
