// react_js/jsview/samples/basic/text/TextGroup.js
import React from 'react';
import TextAlign from "./TextAlign";
import TextFontStyle from "./TextFontStyle";
import TextOverflow from "./TextOverflow";
import TitleBlock from "../TitleBlock";

class TextGroup extends React.Component {
  render() {
    const titleBlockProps = { ColIndex: 2, itemWidth: this.props.itemWidth, itemHeight: this.props.itemHeight };

    return <div id='item-root' style={this.props.style}>
            <TitleBlock {...titleBlockProps} LineIndex={0} titleText="文字对齐" style={{ top: this.props.itemHeight * 0 }}>
                <TextAlign/>
            </TitleBlock>
            <TitleBlock {...titleBlockProps} LineIndex={1} titleText="字体和字号" style={{ top: this.props.itemHeight * 1 }}>
                <TextFontStyle/>
            </TitleBlock>
            <TitleBlock {...titleBlockProps} itemHeight={this.props.itemHeight * 2} LineIndex={2} titleText="文字折行" style={{ top: this.props.itemHeight * 2 }}>
                <TextOverflow/>
            </TitleBlock>
        </div>;
  }
}

export default TextGroup;

// vue3_js/jsview/samples/basic/text/TextGroup.vue
<template>
    <div id='item-root'>
        <ContentBlock :=contentBlockProps :index=0 title="文字对齐" :style="{ top: (itemSides.height * 0)+'px' }">
             <TextAlign/>
        </ContentBlock>
        <ContentBlock :=contentBlockProps :index=1 title="字体和字号" :style="{ top: (itemSides.height * 1)+'px' }">
            <TextFontStyle/>
        </ContentBlock>
        <ContentBlock :="{...contentBlockProps, itemSides: {...itemSides, height:290}}" :index=2 title="文字折行" :style="{ top: (itemSides.height * 2)+'px'}">
            <TextOverflow/>
        </ContentBlock>
    </div>
</template>

<script setup>
import { defineProps, ref } from "vue";
import ContentBlock from '../ContentBlock';
import TextAlign from './TextAlign';
import TextFontStyle from './TextFontStyle';
import TextOverflow from './TextOverflow';

const name = 'DivGroup2';
const props = defineProps({
  contentSize: Object,
  itemSides: Object 
})
</script>


<script jsv-style>
const contentBlockProps = {
    colIndex: 0,
    contentSize: props.contentSize,
    itemSides: props.itemSides
};
</script>
