// vue3_js/jsview/samples/basic/components/div/DivGroup2.vue
<template>
    <div id='item-root'>
        <ContentBlock :=contentBlockProps :index=1 title="Radius(实现圆角)" :style="{ top: itemSides.height*0}">
            <DivRadius/>
        </ContentBlock>
    </div>
</template>

<script setup>
import { defineProps, ref } from "vue";
import ContentBlock from '../ContentBlock';
import DivRadius from './DivRadius';

const name = 'DivGroup2';
const props = defineProps({
  contentSize: Object,
  itemSides: Object 
})
</script>


<script jsv-style>
const contentBlockProps = {
    colIndex: 0,
    contentSize: props.contentSize,
    itemSides: props.itemSides
};
</script>

// react_js/jsview/samples/basic/div/DivGroup2.js
import React from 'react';
import DivRadius from "./DivRadius";
import TitleBlock from "../TitleBlock";

class DivGroup extends React.Component {
  render() {
    const titleBlockProps = { ColIndex: 1, itemWidth: this.props.itemWidth, itemHeight: this.props.itemHeight };

    return <div id='item-root' style={this.props.style}>
            <TitleBlock {...titleBlockProps} LineIndex={0} titleText="Radius(实现圆角)" style={{ top: this.props.itemHeight * 0 }}>
                <DivRadius/>
            </TitleBlock>
        </div>;
  }
}

export default DivGroup;
